apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache # Selects Pods with the label 'app: apache'
  ports:
    - protocol: TCP
      port: 80 # The port the Service itself will listen on
      targetPort: 80 # The port on the Pod that the Service will forward traffic to
  type: LoadBalancer 
