apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  # Main MySQL container
  - name: mysql
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "rootpassword"
    - name: MYSQL_DATABASE
      value: "testdb"
    - name: MYSQL_USER
      value: "testuser"
    - name: MYSQL_PASSWORD
      value: "testpass"
    volumeMounts:
    - name: mysql-logs
      mountPath: /var/log/mysql
    - name: mysql-config
      mountPath: /etc/mysql/conf.d/my.cnf
      subPath: my.cnf
    ports:
    - containerPort: 3306
  # Fluentd sidecar container
  - name: fluentd
    image: fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch
    env:
    - name: FLUENT_ELASTICSEARCH_HOST
      value: "elasticsearch"
    - name: FLUENT_ELASTICSEARCH_PORT
      value: "9200"
    - name: FLUENT_ELASTICSEARCH_SCHEME
      value: "http"
    - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
      value: "false"
    - name: FLUENT_ELASTICSEARCH_INDEX_NAME
      value: "mysql-logs"
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    volumeMounts:
    - name: fluentd-config
      mountPath: /fluentd/etc/fluent.conf
      subPath: fluent.conf
    - name: mysql-logs
      mountPath: /var/log/mysql
      readOnly: true

  volumes:
  # Fluentd configuration
  - name: fluentd-config
    configMap:
      name: fluentd-config-mysql
  # Shared volume for MySQL logs
  - name: mysql-logs
    emptyDir: {}
  - name: mysql-config
    configMap:
      name: mysql-config
